language: python
python: 3.7

install: skip

jobs:
    include:
        - stage: "Test"
          script:
              - ./util/print_header.sh "BALANCED BINARY SEARCH TREE TESTS"
              - pushd balanced_bst && ./test.sh && popd
